language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"

services:
  - mongodb

before_script:
  - composer install
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit --coverage-text --exclude-group server
